# this is my main FastAPI application file

"""
FastAPI Application with Tortoise ORM Database

QUESTION: "How does Tortoise ORM create database tables?"
ANSWER: 
1. Tortoise.init() → Initializes ORM with config
2. Tortoise.generate_schemas() → Creates tables from models
3. Tortoise.close_connections() → Cleanup on shutdown

This happens in the LIFESPAN event, which runs:
- ONCE when app starts
- ONCE when app shuts down
"""

from fastapi import FastAPI, HTTPException, Request, Response, status, Depends
from tortoise.contrib.fastapi import register_tortoise
from config import TORTOISE_ORM, DATABASE_URL
import logging
import tzdata  # Ensure Windows has IANA timezone data for zoneinfo

from models import *

# import the request body schemas
from schemas import *

# set up logging to see Tortoise ORM logs in console
logging.basicConfig(level=logging.INFO)
'''
- logging.basicConfig(level=logging.INFO): This line configures the logging module to display log messages 
at the INFO level and above. 
This means that any log messages generated by Tortoise ORM at the INFO level (or higher severity) will be
printed to the console.
- This is useful for debugging and monitoring database operations, as it allows you to see the SQL queries
that Tortoise ORM is executing, as well as any other relevant information about the database interactions.

- others levels include DEBUG (more detailed logs), WARNING, ERROR, and CRITICAL (only severe issues).
- DEBUG is the most verbose level, showing all logs
- INFO shows general information about app operations
- WARNING shows potential issues that aren't necessarily errors
- ERROR shows actual errors that occur during execution
- CRITICAL shows only the most severe errors that may cause the app to crash

'''
# IMPORTANT: .setLevel() returns None, so you must do this in TWO SEPARATE LINES!
# WRONG: logger = logging.getLogger("tortoise").setLevel(logging.INFO)  # logger becomes None!
# RIGHT: (two lines)
logger = logging.getLogger(__name__)  # Get the logger first
logger.setLevel(logging.INFO)  # THEN set the level

'''
- logging.getLogger(__name__): Gets the logger for this module.
  __name__ is special variable that equals the module name (in this case "main")
  Using __name__ is better practice than hardcoding "tortoise"
  
- logger.setLevel(logging.INFO): Sets the logging level.
  This MODIFIES the logger object in-place and returns None.
  That's why we assign logger BEFORE calling setLevel()!
  
INTERVIEW TIP: This is a common Python mistake!
Students often write: logger = Logger().setLevel(...)
And get None because setLevel() returns nothing.
Always do object creation/retrieval FIRST, then call methods.
'''


"""
Lifespan event

Question : What is the lifespan event in FastAPI and how does it work?
Answer: The lifespan event in FastAPI is a special event that allows us to run code when the application 
        starts up and shuts down.
        We can use the @app.on_event decorator to define functions that will be executed during these events
        
"""


# @asynccontextmanager
async def lifespan(app: FastAPI):
    '''
    lifespan(app: FastAPI): This is an asynchronous context manager function that takes the FastAPI app as 
    an argument. 
    Inside this function, we can define code that will run when the application starts and when it shuts down.
    
    IMPORTANT: The models are already imported at the top of this file (from models import *)
    So they're registered with Tortoise by the time this lifespan runs.
    '''
    logger.info("="*60)
    logger.info(" 🚀 Starting Application ...")
    logger.info("="*60)
    
    try:
        logger.info("📦 Initializing Tortoise ORM...")
        
        # Initialize Tortoise with config
        # The config.py has the database path and model definitions
        await Tortoise.init(config=TORTOISE_ORM)
        
        logger.info("✅ Tortoise initialized")
        logger.info("🏗️  Creating database tables from models...")
        
        # Create all tables based on models
        await Tortoise.generate_schemas()
        
        logger.info("✅ Database tables created successfully")
        
    except Exception as e:
        logger.error(f"❌ Failed to initialize database: {e}")
        raise
    
    logger.info("=" * 60)
    logger.info("✅ DATABASE READY - App is running!")
    logger.info("=" * 60)
    
    yield  # App runs here - requests are processed
    
    # ========== SHUTDOWN CODE ==========
    logger.info("=" * 60)
    logger.info("🛑 SHUTTING DOWN APPLICATION")
    logger.info("=" * 60)
    
    try:
        logger.info("🔌 Closing database connections...")
        await Tortoise.close_connections()
        logger.info("✅ Database closed")
    except Exception as e:
        logger.error(f"❌ Error closing database: {e}")
    
    logger.info("=" * 60)
    logger.info("✅ APPLICATION STOPPED")
    logger.info("=" * 60)

    
    
    
    
    


app = FastAPI(
    title="basic FastAPI app with Tortoise ORM",
    description="A simple FastAPI application that demonstrates how to use Tortoise ORM for database interactions.",
    version="1.0.0",
)

register_tortoise(
    app,
    db_url=DATABASE_URL,
    modules={"models": ["models"]},
    generate_schemas=True,
    add_exception_handlers=True,
)
'''
lifespan=lifespan: This line registers the lifespan event with the FastAPI application.
By passing the lifespan function we defined earlier to the FastAPI constructor, we tell FastAPI to
execute the code in the lifespan function when the application starts and shuts down.
This allows us to set up our database connection and create tables when the app starts, and to
close database connections when the app shuts down, ensuring proper resource management throughout
the lifecycle of the application.
'''


# ============ MIDDLEWARE ============
# MIDDLEWARE EXPLANATION:
# Middleware is code that runs BEFORE your endpoint and AFTER your endpoint returns.
# It sits between the client and your route handler.
# All requests flow through middleware in the order they are added.

from fastapi.middleware.cors import CORSMiddleware
from time import time as get_time

# CORS Middleware - Allow cross-origin requests from specific domains
# In production, replace ["*"] with specific domains like ["https://example.com"]
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # Allow all origins (use specific domains in production!)
    allow_credentials=True,
    allow_methods=["*"],  # Allow GET, POST, PUT, DELETE, etc.
    allow_headers=["*"],  # Allow any headers
)
'''
CORS Middleware Explanation:
- allow_origins=["*"]: Allows requests from any domain. This is OK for learning but NOT safe for production APIs.
- allow_methods=["*"]: Allows all HTTP methods (GET, POST, PUT, DELETE, PATCH, etc.)
- allow_headers=["*"]: Allows clients to send any custom headers

In production, you should whitelist specific domains:
    allow_origins=["https://example.com", "https://app.example.com"]
'''

# Custom Request/Response Logging Middleware
# This middleware logs timing information for every request
from starlette.middleware.base import BaseHTTPMiddleware
from starlette.requests import Request as StarletteRequest
from starlette.responses import Response as StarletteResponse

class RequestLoggingMiddleware(BaseHTTPMiddleware):
    '''
    This middleware logs incoming requests and outgoing responses.
    It measures how long each request takes to process.
    
    INTERVIEW QUESTION: "How would you implement request logging without breaking streaming responses?"
    ANSWER: Use raw ASGI middleware instead of BaseHTTPMiddleware to avoid buffering.
    BaseHTTPMiddleware is easier to understand but slower and buffers the whole response.
    '''
    
    async def dispatch(self, request: StarletteRequest, call_next):
        # Before the request is processed
        start_time = get_time()
        
        # Log the incoming request
        logger.info(f"→ {request.method} {request.url.path} from {request.client.host}")
        
        # Process the request (run the actual endpoint)
        response = await call_next(request)
        
        # After the response is ready
        process_time = get_time() - start_time
        
        # Log the response with timing information
        logger.info(f"← {request.method} {request.url.path} - Status {response.status_code} - {process_time:.3f}s")
        
        # Add custom header showing how long the request took
        response.headers["X-Process-Time"] = str(process_time)
        
        return response

# Add the logging middleware to the app
app.add_middleware(RequestLoggingMiddleware)
'''
Middleware order matters!
Middleware is executed in REVERSE order of how you add it.
So the LAST middleware added (RequestLoggingMiddleware) runs FIRST on incoming requests.
This means logs will show timing including CORS processing.

Order of execution on incoming request:
1. RequestLoggingMiddleware.dispatch() - START
2. CORSMiddleware - runs
3. Your endpoint code - runs
4. Response returned
5. RequestLoggingMiddleware.dispatch() - FINISH (logs and adds header)
'''


@app.get("/")
async def hello():
    return{'data':'hello world'}


@app.get("/about")
async def about():
    return {'data':'this is the content of about page'}




@app.get("/health")
async def health():
    # here we can add some logic to check database connection or other services
    # for now i am simply returning a success message
    return {'status':'ok'}
    
    



@app.post("/api/v1_0/todos", response_model=TodoResponse,status_code=status.HTTP_201_CREATED)
async def create_todo(payload:TodoCreate , request:Request , response:Response):
    '''
    payload:TodoCreate - This means that the request body should be validated against the TodoCreate Pydantic model.
    request:Request - This allows us to access the incoming HTTP request object, which contains information 
            about the request such as headers, query parameters, etc.
    response:Response - This allows us to modify the outgoing HTTP response object, such as setting headers 
            or status codes.
    
    By including these parameters in our endpoint function, we can easily access and manipulate both the 
            incoming request data and the outgoing response data as needed.
    '''
    # create a new Todo item in the database using Tortoise ORM
    # IMPORTANT: In Pydantic V2, use .model_dump() instead of .dict()
    # .dict() was the old Pydantic V1 method (deprecated)
    # .model_dump() is the new V2 method
    todo = await Todo.create(**payload.model_dump())
    '''
    Todo.create(**payload.model_dump()):
    This line creates a new Todo item in the database using Tortoise ORM.
    The payload is an instance of the TodoCreate Pydantic model, which contains the data sent in the request
    body.
    The .model_dump() method (Pydantic V2) converts the Pydantic model instance into a dictionary, 
    which can then be unpacked using ** to pass the fields as keyword arguments to the Todo.create() method.
    This will create a new record in the "todo" table with the data provided in the request body.
    
    
    How the unpacking works:
    If payload.dict() returns {'title': 'Buy groceries', 'description': 'Milk, Bread, Eggs', 'completed': False}
    Then **payload.dict() will unpack this dictionary into keyword arguments like:
    Todo.create(title='Buy groceries', description='Milk, Bread, Eggs', completed=False)
    This is a convenient way to pass all the fields from the Pydantic model directly to the ORM 
    create method without having to manually specify each field.
    
    
    Sql equivalent:
    INSERT INTO todo (title, description, completed) VALUES ('Buy groceries', 'Milk, Bread, Eggs', False);
       
    '''
    
    return todo  # FastAPI will automatically convert this to JSON using the TodoResponse schema

'''
- return todo: This returns the newly created Todo item as the response.
Since we specified response_model=TodoResponse in the endpoint decorator,
FastAPI will automatically convert the Tortoise ORM model instance (todo) into a JSON response that matches 
the TodoResponse schema.
This means that the response will include the fields defined in TodoResponse 
(id, title, description, completed, created_at) and will be properly formatted as JSON for the client
to consume.


Who will convert the responsed JSON to Http response?
FastAPI will handle the conversion of the returned data (in this case, the Todo model instance)
into an HTTP response. 
When you return a Tortoise ORM model instance from an endpoint, 
FastAPI will automatically use the response_model (TodoResponse) to serialize the data into JSON format and
create an HTTP response with the appropriate content type and status code.

'''


# Creating a dependecy function of checking if todo_id exists in the  table


async def get_todo_by_id(todo_id:int) -> Todo:
    todo = await Todo.get_or_none(id=todo_id)
    
    if todo is None:
        raise HTTPException(
            status_code = status.HTTP_404_NOT_FOUND,
            detail = f"Todo with id {todo_id} not found"
        )
    
    return todo    
  
  

# now creating an endpoint to fetch a todo by id using the above dependency function


@app.get("/api/v1_0/todos/{todo_id}", response_model=TodoResponse, status_code=status.HTTP_200_OK)
async def get_todo(todo: Todo = Depends(get_todo_by_id)):
    
        """
        The 'todo' parameter gets the TODO OBJECT automatically.
        Depends() called get_todo_by_id(todo_id) BEFORE this function runs.
        """
        return todo  # FastAPI converts this to JSON using TodoResponse schema
    

'''
  How it works:
1. Client: GET /api/v1_0/todos/1
           ↓
2. FastAPI extracts: todo_id = 1
           ↓
3. FastAPI calls the DEPENDENCY: get_todo_by_id(1)
           ↓
4. Dependency queries DB:
   - Found? → return the todo object
   - Not found? → raise HTTPException(404) ← ENDPOINT NEVER RUNS!
           ↓
5. If dependency succeeded, 'todo' = the fetched object
           ↓
6. Endpoint function executes and returns it as JSON

'''
    
# without the dependecy , we will write the same endpoint like this 

@app.get("/api/v1_0/todos_by_id/{todo_id}", response_model=TodoResponse, status_code=status.HTTP_200_OK)
async def fetch_todo_by_id(todo_id : int, respnse:Response , request:Request):
    todo= await Todo.get_or_none(id=todo_id)
    
    if todo is None:
        raise HTTPException(
            status_code = status.HTTP_404_NOT_FOUND,
            detail = f"Todo with id {todo_id} not found"
        )
        
    return todo    
    
    

# You have an endpoint that must accept both JSON and form data. How do you design it in FastAPI?

# I will create a dependency parser function that will return unified Pydandic model


async def perse_user_info(request : Request) -> UserCreate:
    content_type = request.headers.get("content_type","")
    
    if "application/json" in content_type:
        data = await request.json()
    
    elif "form" in content_type:
        form = await request.form()
        data = dict(form)
    else:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Content type not supported"
        )       
    
    return UserCreate(**data)   

    '''
    (**data) unpacks the dictionary into keyword arguments for the UserCreate Pydantic model.
    For example, if data = {'name': 'Alice', 'email': 'alice@example  com'},
    then UserCreate(**data) is equivalent to UserCreate(name='Alice', email= 'alice@example.com') 
    '''
    

@app.post("/api/v1_0/users", response_model=UserResponse, status_code=status.HTTP_201_CREATED)
async def create_user(payload: UserCreate = Depends(perse_user_info)):
    '''
    dependency perse_user_info will parse the incoming request based on its content type (JSON or form data) 
    and return a UserCreate Pydantic model instance.
    The endpoint can then use this parsed data to create a new user in the database, 
    and return the created user as a response.
    '''
    user = await Users.create(**payload.model_dump())

    return user  # FastAPI will convert this to JSON using UserResponse schema